---
#   It allows you to choose if this plugin works or doesn't work on splash potions
enable-splash-potion: true

#   It allows you to choose if this plugin works or doesn't work on potions
enable-potion: true

#   It allows you to disable / enable the plugin
enable-plugin: true

#   WATER = 0;
#	MUNDANE = 1;
#	LONG_MUNDANE = 2;
#	THICK = 3;
#	AWKWARD = 4;
#	NIGHT_VISION = 5;
#	LONG_NIGHT_VISION = 6;
#	INVISIBILITY = 7;
#	LONG_INVISIBILITY = 8;
#	LEAPING = 9;
#	LONG_LEAPING = 10;
#	STRONG_LEAPING = 11;
#	FIRE_RESISTANCE = 12;
#	LONG_FIRE_RESISTANCE = 13;
#	SWIFTNESS = 14;
#	LONG_SWIFTNESS = 15;
#	STRONG_SWIFTNESS = 16;
#	SLOWNESS = 17;
#	LONG_SLOWNESS = 18;
#	WATER_BREATHING = 19;
#	LONG_WATER_BREATHING = 20;
#	HEALING = 21;
#	STRONG_HEALING = 22;
#	HARMING = 23;
#	STRONG_HARMING = 24;
#	POISON = 25;
#	LONG_POISON = 26;
#	STRONG_POISON = 27;
#	REGENERATION = 28;
#	LONG_REGENERATION = 29;
#	STRONG_REGENERATION = 30;
#	STRENGTH = 31;
#	LONG_STRENGTH = 32;
#	STRONG_STRENGTH = 33;
#	WEAKNESS = 34;
#	LONG_WEAKNESS = 35;
#	WITHER = 36;

#   use numbers to identify which potions the plugin is going to work on
#   Example: world1: [36,35,5,6,9,21]
active-on:
  world123: [36,35,5,6,9,21]
  PotFFA: [28]
...